### ISSUE TITLE
May I send add a Traditional Chinese version of the sample config?

### ISSUE THREAD

**Issue by PeterDaveHello** [lziad/Telegram-CAPTCHA-bot#5]
Hi @lziad,

May I send a pull request to add a Traditional Chinese version of the `config.example.js`? Maybe named as `config.example.zh_tw.js`?

Thank you!

**Comment by fossifer** [comment]
Hi, you may simply merge them into the current sample config and use another key, like:
```
"*": {
    (This is the current Simplified Chinese sample config)
},
"Your Traditional Chinese Group ID": {
    "msg_self_introduction": "Some Nice Traditional Chinese Goes Here",
}
```
Thanks for participating!

**Comment by PeterDaveHello** [comment]
Thanks! I'll try that.
