### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zlhdd108** [lziad/Telegram-CAPTCHA-bot#6]
![image](https://user-images.githubusercontent.com/16465666/69909503-dc989c80-1436-11ea-8cc6-78d206f525bc.png)
python3 运行报错

**Comment by fossifer** [comment]
`f-string` 需要 Python 3.6 或以上才能使用，所以你可能需要更新 Python 版本或者把代码里面的 `f-string` 全部改成 `str.format`，如
```
logging.warning(f'UserNotParticipantError on challenge_user: user={target.id}, chat={chat.id}')
```
改为
```
logging.warning('UserNotParticipantError on challenge_user: user={}, chat={}'.format(target.id, chat.id))
```

**Comment by zlhdd108** [comment]
> `f-string` 需要 Python 3.6 或以上才能使用，所以你可能需要更新 Python 版本或者把代码里面的 `f-string` 全部改成 `str.format`，如
> 
> ```
> logging.warning(f'UserNotParticipantError on challenge_user: user={target.id}, chat={chat.id}')
> ```
> 
> 改为
> 
> ```
> logging.warning('UserNotParticipantError on challenge_user: user={}, chat={}'.format(target.id, chat.id))
> ```

用python3.7.5，又成这样了……
![image](https://user-images.githubusercontent.com/16465666/69927310-838e3e80-14f2-11ea-9512-0f840022ca4e.png)

**Comment by fossifer** [comment]
得把 `config.json` 里面 // 和 /* */ 的注释都删掉。

**Comment by zlhdd108** [comment]
> 得把 `config.json` 里面 // 和 /* */ 的注释都删掉。

好的，可以了，谢谢
